name: Docker Image CI

on: [push]

jobs:

  build-server:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: marce1994/multiplayer-tp1
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: Dockerfile
        cache: true
